# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1006, 651)
        MainWindow.setStyleSheet("/* =========================================\n"
"   VERIFIED FRUTIGER AERO STYLESHEET (CLEAN)\n"
"   ========================================= */\n"
"\n"
"QMainWindow {\n"
"    background-color: #E6F3F7; \n"
"}\n"
"\n"
"QGroupBox {\n"
"    background-color: rgba(255, 255, 255, 0.7); \n"
"    border: 1px solid #99CCFF;\n"
"    border-radius: 12px;\n"
"    margin-top: 10px;\n"
"    font: 12pt \"Segoe UI\";\n"
"    color: #004D66; \n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 10px;\n"
"    background-color: #99CCFF; \n"
"    color: #FFFFFF; \n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                     stop: 0 #77DD77, \n"
"                                     stop: 1 #4CAF50); \n"
"    color: white;\n"
"    font: 10pt \"Segoe UI Semibold\";\n"
"    border: 1px solid #388E3C;\n"
"    border-radius: 8px;\n"
"    padding: 8px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #82E0AA;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid #0099CC; \n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"    font: 11pt \"Segoe UI\";\n"
"}\n"
"QLabel {\n"
"    font-family: \"Segoe UI\", Helvetica, Arial, sans-serif;\n"
"    color: #004D66; \n"
"    padding: 3px; \n"
"    background-color: transparent;\n"
"}\n"
"/* Style for key values like 29.5 °C */\n"
"QLabel[class=\"ValueLabel\"] {\n"
"    /* Highly legible, bold digital font style */\n"
"    font-family: \"Segoe UI Black\", \"Segoe UI Semibold\", Arial, sans-serif;\n"
"    font-weight: 800; /* Extra bold */\n"
"    \n"
"    /* Aquatic blue/cyan color */\n"
"    color: #0088CC; \n"
"    \n"
"    /* Text shadow creates the signature soft glow and depth */\n"
"    text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.3), \n"
"                 0 0 10px rgba(0, 150, 200, 0.7); \n"
"    \n"
"    /* You will manually set font-size: 24pt (or similar) on this element */\n"
"    padding: 5px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(319, 281))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.curtainInput = QtWidgets.QLineEdit(self.groupBox_2)
        self.curtainInput.setObjectName("curtainInput")
        self.gridLayout_8.addWidget(self.curtainInput, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_8.addWidget(self.pushButton, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("/* --- AGGRESSIVE FEATURE FONT OVERRIDE --- */\n"
"QLabel[class=\"ValueLabel\"] {\n"
"    font: 24pt \"Segoe UI Black\"; /* Increased size and highly visible font */\n"
"    font-weight: 900; /* Ensures the text is rendered extremely bold */\n"
"    color: #0088CC; /* Bright Aquatic Blue */\n"
"    text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.4), \n"
"                 0 0 15px rgba(0, 150, 200, 0.9); /* Stronger glow/shadow */\n"
"    min-height: 40px; /* Ensures vertical space for the large font */\n"
"    padding: 5px;\n"
"}")
        self.label_6.setTextFormat(Qt.PlainText)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMaximumSize(QtCore.QSize(319, 268))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.outside = QtWidgets.QPushButton(self.groupBox_4)
        self.outside.setObjectName("outside")
        self.gridLayout_7.addWidget(self.outside, 1, 0, 1, 1)
        self.movie = QtWidgets.QPushButton(self.groupBox_4)
        self.movie.setObjectName("movie")
        self.gridLayout_7.addWidget(self.movie, 0, 0, 1, 1)
        self.curtainUpdate = QtWidgets.QPushButton(self.groupBox_4)
        self.curtainUpdate.setObjectName("curtainUpdate")
        self.gridLayout_7.addWidget(self.curtainUpdate, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMaximumSize(QtCore.QSize(319, 268))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.guests = QtWidgets.QPushButton(self.groupBox_3)
        self.guests.setObjectName("guests")
        self.gridLayout_3.addWidget(self.guests, 2, 0, 1, 1)
        self.sweat = QtWidgets.QPushButton(self.groupBox_3)
        self.sweat.setObjectName("sweat")
        self.gridLayout_3.addWidget(self.sweat, 1, 0, 1, 1)
        self.cold = QtWidgets.QPushButton(self.groupBox_3)
        self.cold.setObjectName("cold")
        self.gridLayout_3.addWidget(self.cold, 0, 0, 1, 1)
        self.acUpdate = QtWidgets.QPushButton(self.groupBox_3)
        self.acUpdate.setObjectName("acUpdate")
        self.gridLayout_3.addWidget(self.acUpdate, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(319, 281))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.acLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.acLabel.setFont(font)
        self.acLabel.setAlignment(Qt.AlignCenter)
        self.acLabel.setObjectName("acLabel")
        self.gridLayout_4.addWidget(self.acLabel, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.acInput = QtWidgets.QLineEdit(self.groupBox)
        self.acInput.setObjectName("acInput")
        self.gridLayout_4.addWidget(self.acInput, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 3, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setMaximumSize(QtCore.QSize(397, 561))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.ambientTemp = QtWidgets.QLabel(self.groupBox_5)
        self.ambientTemp.setText("")
        self.ambientTemp.setObjectName("ambientTemp")
        self.gridLayout_6.addWidget(self.ambientTemp, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        self.desiredTemp = QtWidgets.QLabel(self.groupBox_5)
        self.desiredTemp.setText("")
        self.desiredTemp.setObjectName("desiredTemp")
        self.gridLayout_6.addWidget(self.desiredTemp, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 2, 0, 1, 1)
        self.fanSpeed = QtWidgets.QLabel(self.groupBox_5)
        self.fanSpeed.setText("")
        self.fanSpeed.setObjectName("fanSpeed")
        self.gridLayout_6.addWidget(self.fanSpeed, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 3, 0, 1, 1)
        self.outdoorTemp = QtWidgets.QLabel(self.groupBox_5)
        self.outdoorTemp.setText("")
        self.outdoorTemp.setObjectName("outdoorTemp")
        self.gridLayout_6.addWidget(self.outdoorTemp, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 4, 0, 1, 1)
        self.curtainStatus = QtWidgets.QLabel(self.groupBox_5)
        self.curtainStatus.setText("")
        self.curtainStatus.setObjectName("curtainStatus")
        self.gridLayout_6.addWidget(self.curtainStatus, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 5, 0, 1, 1)
        self.lightIntensity = QtWidgets.QLabel(self.groupBox_5)
        self.lightIntensity.setText("")
        self.lightIntensity.setObjectName("lightIntensity")
        self.gridLayout_6.addWidget(self.lightIntensity, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 6, 0, 1, 1)
        self.connectionStatus = QtWidgets.QLabel(self.groupBox_5)
        self.connectionStatus.setText("")
        self.connectionStatus.setObjectName("connectionStatus")
        self.gridLayout_6.addWidget(self.connectionStatus, 6, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 7, 0, 1, 1)
        self.outdoorPressure = QtWidgets.QLabel(self.groupBox_5)
        self.outdoorPressure.setText("")
        self.outdoorPressure.setObjectName("outdoorPressure")
        self.gridLayout_6.addWidget(self.outdoorPressure, 7, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 8, 0, 1, 1)
        self.acPort = QtWidgets.QLabel(self.groupBox_5)
        self.acPort.setText("")
        self.acPort.setObjectName("acPort")
        self.gridLayout_6.addWidget(self.acPort, 8, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 9, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 10, 0, 1, 1)
        self.curtainPort = QtWidgets.QLabel(self.groupBox_5)
        self.curtainPort.setText("")
        self.curtainPort.setObjectName("curtainPort")
        self.gridLayout_6.addWidget(self.curtainPort, 10, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 11, 0, 1, 1)
        self.curtainBaudrate = QtWidgets.QLabel(self.groupBox_5)
        self.curtainBaudrate.setText("")
        self.curtainBaudrate.setObjectName("curtainBaudrate")
        self.gridLayout_6.addWidget(self.curtainBaudrate, 11, 1, 1, 1)
        self.acBaudrate = QtWidgets.QLabel(self.groupBox_5)
        self.acBaudrate.setText("")
        self.acBaudrate.setObjectName("acBaudrate")
        self.gridLayout_6.addWidget(self.acBaudrate, 9, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_5, 0, 2, 2, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1006, 22))
        self.menubar.setObjectName("menubar")
        self.menuAir_Conditioner = QtWidgets.QMenu(self.menubar)
        self.menuAir_Conditioner.setObjectName("menuAir_Conditioner")
        self.menuCurtain = QtWidgets.QMenu(self.menubar)
        self.menuCurtain.setObjectName("menuCurtain")
        self.exit = QtWidgets.QMenu(self.menubar)
        self.exit.setObjectName("exit")
        self.menuSave = QtWidgets.QMenu(self.menubar)
        self.menuSave.setObjectName("menuSave")
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuTemp = QtWidgets.QAction(MainWindow)
        self.menuTemp.setObjectName("menuTemp")
        self.menuControl = QtWidgets.QAction(MainWindow)
        self.menuControl.setObjectName("menuControl")
        self.save = QtWidgets.QAction(MainWindow)
        self.save.setObjectName("save")
        self.menuAir_Conditioner.addAction(self.menuTemp)
        self.menuCurtain.addAction(self.menuControl)
        self.menuSave.addAction(self.save)
        self.menubar.addAction(self.menuAir_Conditioner.menuAction())
        self.menubar.addAction(self.menuCurtain.menuAction())
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.exit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Home Automation System"))
        self.pushButton.setText(_translate("MainWindow", "APPLY"))
        self.label_6.setText(_translate("MainWindow", "Curtain Control"))
        self.label_7.setText(_translate("MainWindow", "Enter Desired Curtain Status (0.0% to 100.0%)"))
        self.outside.setText(_translate("MainWindow", "I Want To See The Outside World"))
        self.movie.setText(_translate("MainWindow", "I Am Watching A Movie"))
        self.curtainUpdate.setText(_translate("MainWindow", "UPDATE"))
        self.guests.setText(_translate("MainWindow", "I Have Guests Over"))
        self.sweat.setText(_translate("MainWindow", "I Am Sweating"))
        self.cold.setText(_translate("MainWindow", "I Am Cold"))
        self.acUpdate.setText(_translate("MainWindow", "UPDATE"))
        self.acLabel.setText(_translate("MainWindow", "Air Conditioner"))
        self.label.setText(_translate("MainWindow", "Enter Desired Temperature (Range 10.0-50.0)"))
        self.pushButton_2.setText(_translate("MainWindow", "APPLY"))
        self.label_10.setText(_translate("MainWindow", "Home Ambient Temperature"))
        self.label_8.setText(_translate("MainWindow", "Home Desired Temperature"))
        self.label_2.setText(_translate("MainWindow", "Fan Speed"))
        self.label_4.setText(_translate("MainWindow", "Outdoor Temperature"))
        self.label_11.setText(_translate("MainWindow", "Curtain Status"))
        self.label_9.setText(_translate("MainWindow", "Light Intensity"))
        self.label_5.setText(_translate("MainWindow", "Connection Status"))
        self.label_3.setText(_translate("MainWindow", "Outdoor Pressure"))
        self.label_12.setText(_translate("MainWindow", "AC Connection Port"))
        self.label_13.setText(_translate("MainWindow", "AC Connection Baudrate"))
        self.label_14.setText(_translate("MainWindow", "Curtain Connection Port"))
        self.label_15.setText(_translate("MainWindow", "Curtain Connection Baudrate"))
        self.menuAir_Conditioner.setTitle(_translate("MainWindow", "Air Conditioner"))
        self.menuCurtain.setTitle(_translate("MainWindow", "Curtain Control"))
        self.exit.setTitle(_translate("MainWindow", "Exit"))
        self.menuSave.setTitle(_translate("MainWindow", "Save "))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.menuTemp.setText(_translate("MainWindow", "Set Temperature"))
        self.menuControl.setText(_translate("MainWindow", "Control"))
        self.save.setText(_translate("MainWindow", "Save Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
